# Install pre-commit by running "pip install pre-commit".
# Create a ".pre-commit-config.yaml" file with under your git repo root.
# Then run "pre-commit install".
# Each time you run "git commit", it will automatically check a lot of things for you and fix code styles.
# If modification is applied by pre-commit, simple do "git add -A" then commit again.
# Remember to unstage any large files detected by pre-commit.

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-added-large-files
      args: ['--maxkb=49000']  # max file size 49MB

- repo: local
  hooks:
    - id: isort
      name: isort
      entry: "isort --multi-line=3 --trailing-comma --force-grid-wrap=0 --use-parentheses --line-width=119 -rc -ws ."
      language: system
      types: [python]
    - id: black
      name: black
      entry: "black --skip-string-normalization --line-length=119 ."
      language: system
      types: [python]
