repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-added-large-files
# - repo: https://github.com/psf/black
#   rev: 19.10b0
#   hooks:
#     - id: black
#       args: [--skip-string-normalization", "--line-length=119" ]
# - repo: https://github.com/pycqa/isort
#   rev: "5.6.4"
#   hooks:
#     - id: isort
#       args: ["--profile", "black", "--filter-files", "--multi-line=3", "--trailing-comma", "--force-grid-wrap=0",
#         "--use-parentheses", "--line-width=119", "-rc", "-ws"]
