# Copyright (c) 2020-2021, NVIDIA CORPORATION.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: "Release Neural Modules"

on:
  workflow_dispatch:
    inputs:
      release-ref:
        description: Ref (SHA or branch name) to release
        required: true
        type: string
      version-bump-branch:
        description: Branch for version bump
        required: true
        type: string
      dry-run:
        description: Do not publish a wheel and GitHub release.
        required: true
        default: true
        type: boolean
      create-gh-release:
        description: Create a GitHub release
        required: true
        default: true
        type: boolean
      generate-changelog:
        description: Generate changelog
        required: false
        default: true
        type: boolean
      publish-docs:
        description: Publish docs
        required: false
        default: false
        type: boolean
      gh-release-from-tag:
        description: Tag of previous release for changelog builder
        required: false
        type: string
        default: ""
jobs:
  release:
    uses: NVIDIA-NeMo/FW-CI-templates/.github/workflows/_release_library.yml@v0.76.1
    with:
      release-ref: ${{ inputs.release-ref }}
      python-package: nemo
      python-version: "3.10"
      library-name: Neural Modules
      dry-run: ${{ inputs.dry-run }}
      version-bump-branch: ${{ inputs.version-bump-branch }}
      create-gh-release: ${{ inputs.create-gh-release }}
      app-id: ${{ vars.BOT_ID }}
      gh-release-use-changelog-builder: ${{ inputs.generate-changelog }}
      publish-docs: ${{ inputs.publish-docs }}
      gh-release-from-tag: ${{ inputs.gh-release-from-tag }}
    secrets:
      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      SLACK_WEBHOOK_ADMIN: ${{ secrets.SLACK_WEBHOOK_ADMIN }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_RELEASE_ENDPOINT }}
      PAT: ${{ secrets.PAT }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_PWD: ${{ secrets.SSH_PWD }}
      BOT_KEY: ${{ secrets.BOT_KEY }}
      AWS_ASSUME_ROLE_ARN: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AKAMAI_HOST: ${{ secrets.AKAMAI_HOST }}
      AKAMAI_CLIENT_TOKEN: ${{ secrets.AKAMAI_CLIENT_TOKEN }}
      AKAMAI_CLIENT_SECRET: ${{ secrets.AKAMAI_CLIENT_SECRET }}
      AKAMAI_ACCESS_TOKEN: ${{ secrets.AKAMAI_ACCESS_TOKEN }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
